Capt/Controllers/InfoController.cs
/*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capt.Controllers
{
	/// <summary>
	/// Controller for the mostly-static general information pages.
	/// </summary>
	public class InfoController : Controller
    {
        
		/// <summary>
		/// Show the "About this site" page.
		/// </summary>
		/// <returns></returns>
		public ActionResult About()
        {
            return View();
        }

		/// <summary>
		/// Show the "Contact us" page.
		/// </summary>
		/// <returns></returns>
		public ActionResult Contact()
		{
			ViewBag.EmailAddress = System.Configuration.ConfigurationManager.AppSettings["EmailsFrom"];

			return View();
		}

		/// <summary>
		/// Show the terms and conditions page.
		/// </summary>
		/// <returns></returns>
		public ActionResult Conditions()
		{
			return View();
		}

		/// <summary>
		/// Show the privacy policy.
		/// </summary>
		/// <returns></returns>
		public ActionResult Privacy()
		{
			return View();
		}

    }
}

Capt/Controllers/PictureController.cs
/*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capt.Models;
using Capt.Services;

namespace Capt.Controllers
{
	/// <summary>
	/// Mostly just some scaffolded actions to be used with ugly, scaffolded views to do some basic admin stuff.  
	/// Nothing user-facing here.
	/// </summary>
	[Authorize(Roles = "Administrator")]
	public class PictureController : Controller
	{

		private IPictureService _pictureService;


		/// <summary>
		/// Create an instance of this controller with the specified service
		/// </summary>
		/// <param name="pictureRepo"></param>
		/// <param name="licenseRepo"></param>
		public PictureController(IPictureService pictureService)
		{
			_pictureService = pictureService;

			var LicenseOptions = new List<SelectListItem>();
			var licenses = _pictureService.GetAllLicenses();
			foreach(var license in licenses)
			{
				LicenseOptions.Add(
					new SelectListItem()
					{
						Value = license.Id.ToString(),
						Text = license.Description
					}
				);
			}

			ViewBag.LicenseOptions = LicenseOptions;

		}

		/// <summary>
		/// Create an instance of this controller with the default repositories.
		/// </summary>
		public PictureController()
			: this(new PictureService())
		{
		}

		//
		// GET: /Picture/Details/5
		public ActionResult Details(int id)
		{
			Picture pic = _pictureService.GetPictureById(id, ViewBag.IsAdminStuffShown);

			ViewBag.Picture = pic;


			return View(pic);

		}

		//
		// GET: /Picture/Create
		public ActionResult Create()
		{
			Picture pic = new Picture()
			{
				IsNSFW = false,
				IsPrivate = false,
				IsVisible = true,
				Activates = DateTime.UtcNow
			};

			return View(pic);
		}

		//
		// POST: /Picture/Create

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Create(Picture newPicture)
		{
			try
			{

				if (!ModelState.IsValid)
				{
					return View();
				}

				newPicture.Guid = Guid.NewGuid();
				newPicture.User = Session["User"] as User;
				newPicture.Event = new Event(EventType.PictureCreated);

				_pictureService.SavePicture(newPicture);

				return RedirectToAction("Index", "PictureCaptions");
			}
			catch
			{
				return View();
			}
		}

		//
		// GET: /Picture/Edit/5
		public ActionResult Edit(int id)
		{
			return View(_pictureService.GetPictureById(id, ViewBag.IsAdminStuffShown));
		}

		//
		// POST: /Picture/Edit/5

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Edit(int id, Picture editedPicture)
		{
			try
			{
				if (!ModelState.IsValid)
				{
					return View();
				}

				_pictureService.SavePicture(editedPicture);

				return View();
			}
			catch
			{
				return View();
			}
		}

		//
		// GET: /Picture/Delete/5
		public ActionResult Delete(int id)
		{
			return View(_pictureService.GetPictureById(id, ViewBag.IsAdminStuffShown));
		}

		//
		// POST: /Picture/Delete/5

		[HttpPost]
		public ActionResult Delete(int id, Picture picture)
		{
			_pictureService.DeletePicture(id);
			return RedirectToAction("Index", "PictureCaptions");
		}

	}
}

Capt/Views/Shared/Error404.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@{
    ViewBag.Title = "Page Not Found";
}

<h2>@ViewBag.SiteName could not find what you're looking for.</h2>

<p>
    @ViewBag.SiteName suggests you take a look <a href="/">the home page</a>.
</p>

Capt/Views/Shared/PictureCaptionMenuPartial.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
<ul class="menu" id="pictures_or_captions_menu">
    <li>
        @if (ViewContext.RouteData.Values["Controller"].ToString() == "PictureCaptions")
        {
            @:pictures
        }
        else
        {
            @Html.ActionLink("pictures", "Index", "PictureCaptions", null, null)
        }
        @Html.ActionLink("(rss)", "IndexRss", "PictureCaptions", new { }, new { @class = "rss_link" })
    </li>
    <li>
        @if (ViewContext.RouteData.Values["Controller"].ToString() == "CaptionForPicture")
        {
            @:captions
        }
        else
        {
            @Html.ActionLink("captions", "Index", "CaptionForPicture", null, null)
        }
        @Html.ActionLink("(rss)", "IndexRss", "CaptionForPicture", new { }, new { @class = "rss_link" })
    </li>
</ul>

Capt/Views/Shared/_Layout.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@using Capt.Models;
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>
        <meta charset="utf-8" />

        <link rel="alternate" type="application/rss+xml" title="Latest Pictures (RSS 2.0)" href="@Url.Action("IndexRss", "PictureCaptions")" />
        <link rel="alternate" type="application/rss+xml" title="Latest Captions (RSS 2.0)" href="@Url.Action("IndexRss", "CaptionForPicture")" />
        
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        @Html.Action("Include", "Analytics", new { Area = "Analytics" })
        @Html.Action("Include", "Cdn", new { Area = "Cdn" })

        <script type="text/javascript" src=@Url.Content("~/Scripts/CountDown.js")></script>

    </head>
    <body>
        <div class="page">
            <header>
                <div id="title">
                    <a href="/"><h1>@ViewBag.SiteName</h1></a>
                </div>
                <nav>
                    <ul id="topmenu" class="menu">
                        @if (Request.IsAuthenticated)
                        {
                            var user = (User)Session["User"];
                            object routeValues = null;
                            if (String.IsNullOrWhiteSpace(user.Name))
                            {
                                routeValues = new { userName = user.Id };
                            }
                            else
                            {
                                routeValues = new { userName = user.Name };
                            }
                                
                            <li id="topmenu_score">
                                @Html.ActionLink(
                                    @String.Format((user.Score == 1 ? "you have {0} point" : "you have {0} points"), user.Score),
                                    "IndexByUser", "CaptionForPicture", routeValues, new { })
                            </li>
                        }

                        <li>@Html.ActionLink("home", "Index", "PictureCaptions")</li>

                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("log off", "LogOff", "Account")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("log on", "LogOn", "Account", new { ReturnUrl = Request.Url }, new { })</li>
                            <li>@Html.ActionLink("sign up", "LogOn", "Account", new { ReturnUrl = Request.Url }, new { })</li>
                        }


                        @if (ViewBag.IsAdminStuffShown)
                        {
                            <li>@Html.ActionLink("add picture", "Create", "Picture", null, new { @class = "admin_option" })</li>
                            <li>@Html.ActionLink("users", "Index", "User", null, new { @class = "admin_option" })</li>
                        }

					    @if (User.IsInRole("Administrator"))
                        {
						    <li>@Html.ActionLink("toggle privileges", "TogglePrivilegeMode", "Account", new { ReturnUrl = Request.Url }, new { @class = "admin_option" })</li>
                        }

                    </ul>
                </nav>
                <div id="next_picture_countdown">
                    <div id="next_picture_countdown_clock"></div>
                    @if (!String.IsNullOrWhiteSpace(ViewBag.NextPictureActivates))
                    { 
                        <script language="JavaScript">
                            StartCountDown(
                                "next_picture_countdown_clock",
                                "@ViewBag.NextPictureActivates",
                                "next picture in %%H%% hours, %%M%% minutes, %%S%% seconds",
                                "New picture! Reload your browser!"
                            );
                        </script>        
                    }
                </div>
                <div class="clear" />
            </header>
            <section id="main">
                @RenderBody()
            </section>
            <footer>
                    <ul id="top_menu" class="menu">
                        <li>@Html.ActionLink("about", "About", "Info")</li>
                        <li>@Html.ActionLink("contact", "Contact", "Info")</li>
                        <li>@Html.ActionLink("terms & conditions", "Conditions", "Info")</li>
                        <li>@Html.ActionLink("privacy policy", "Privacy", "Info")</li>
                        <li><a href="http://www.seanmccleary.info/projects/capt">powered by capt</a></li>
                    </ul>
                    <p style="text-align: right;">
                        All content copyrighted by original authors and licensed under a <a href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.
                        <a href="http://creativecommons.org/licenses/by-sa/3.0/"><img style="vertical-align: middle;" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /></a>
                    </p>
            </footer>
        </div>
    </body>
</html>