Capt/Controllers/CaptionController.cs
/*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capt.Models;
using Capt.Services;

namespace Capt.Controllers
{

	/// <summary>
	/// A very basic, scaffolded controller for the Caption model.  This is only used for ugly admin stuff, not for
	/// anything user-facing.
	/// </summary>
	[Authorize(Roles = "Administrator")]
	public class CaptionController : Controller
    {

		private IPictureService _pictureService;

		public CaptionController(IPictureService pictureService)
		{
			_pictureService = pictureService; ;
		}

		public CaptionController()
			: this(new PictureService())
		{
		}

        //
        // GET: /Caption/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Caption/Details/5

        public ActionResult Details(int id)
        {
            return View(_pictureService.GetCaptionById(id, ViewBag.IsAdminStuffShown));
        }

        
        //
        // GET: /Caption/Edit/5
 
        public ActionResult Edit(int id)
        {
			return View(_pictureService.GetCaptionById(id, ViewBag.IsAdminStuffShown));
        }

        //
        // POST: /Caption/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, Caption caption)
        {
            try
            {
				if (!ModelState.IsValid)
				{
					return View();
				}

				_pictureService.SaveCaption(caption);

				return View();
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Caption/Delete/5
 
        public ActionResult Delete(int id)
        {
			return View(_pictureService.GetCaptionById(id, ViewBag.IsAdminStuffShown));
        }

        //
        // POST: /Caption/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, Caption caption)
        {
            try
            {
				caption = _pictureService.GetCaptionById(id, ViewBag.IsAdminStuffShown);
				_pictureService.DeleteCaption(caption);
                return RedirectToAction("Create", "PictureCaptions", new { pictureId = caption.PictureId });
            }
            catch
            {
                return View();
            }
        }
    }
}

Capt/Controllers/CaptionForPictureController.cs
/*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Web;
using System.Web.Mvc;
using Capt.Helpers;
using Capt.Models;
using Capt.Services;

namespace Capt.Controllers
{
	/// <summary>
	/// The controller for the CaptionForPictureViewModel.
	/// </summary>
	public class CaptionForPictureController : Controller
    {
		/// <summary>
		/// Our account service we'll be a-usin'.
		/// </summary>
		private IAccountService _accountService;

		/// <summary>
		/// Our picture service this controller will use
		/// </summary>
		private IPictureService _pictureService;

		/// <summary>
		/// Constructor which allows you to specify your own services.
		/// </summary>
		/// <param name="accountService">The account service to use for this controller</param>
		/// <param name="pictureService">The picture service to use for this controller</param>
		public CaptionForPictureController(IAccountService accountService, IPictureService pictureService)
		{
			_accountService = accountService;
			_pictureService = pictureService;
		}

		/// <summary>
		/// Zero-argument constructor will choose the most appropriate repositories for this environment.
		/// </summary>
		public CaptionForPictureController()
			: this(new AccountService(), new PictureService())
		{
		}

		/// <summary>
		/// The action for the RSS "Captions" RSS feed.
		/// </summary>
		/// <returns></returns>
		[OutputCache(Duration = 3600)]
		public RssActionResult IndexRss()
		{
			List<SyndicationItem> items = new List<SyndicationItem>();

			var captions = _pictureService.GetAllCaptions(false, 10);

			var urlHelper = new UrlHelper(this.ControllerContext.RequestContext);

			string urlPrefix = "http://" + Request.Url.Host;
			if (!Request.Url.IsDefaultPort)
			{
				urlPrefix += ":" + Request.Url.Port;
			}

			var baseUri = new Uri(urlPrefix + urlHelper.Action("Index", "CaptionForPicture"));


			foreach (var caption in captions)
			{
				var uri = new Uri(urlPrefix + urlHelper.Action("Create", "PictureCaptions", new { pictureId = caption.Picture.Id }));
				var authorUrl = urlPrefix + urlHelper.Action("IndexByUser", "CaptionForPicture", new { userName = caption.User.Name });

				string html = String.Format(
					@"<div style=""text-align: center; padding-bottom: 15px;"">
						<div style=""margin-bottom: 10px; text-align: left; display: inline-block; background-color: #F1F1F1; padding: 5px; zoom:1; display:inline;"">
							<a href=""{5}""><img style=""border: none;"" src=""{0}"" /></a><br />
							<a href=""{3}""><img src=""{4}"" /></a>
							<a href=""{1}"">{2}</a>
						</div>
						<br /><span style=""line-height: 150%; font-size: 200%;"">{6}</span>
						<br /><span>&mdash; {7}</span>
						<br /><a style=""line-height: 150%; font-size: 200%;"" href=""{5}"">Got a good caption for this?</a>
					</div>",
					caption.Picture.Url, // 0
					caption.Picture.AttributionUrl, // 1
					caption.Picture.Attribution, // 2
					caption.Picture.License.InfoUrl, // 3
					caption.Picture.License.ImageUrl, // 4
					uri.ToString(), // 5
					caption.Text, // 6
					caption.User.Name != null && !caption.IsAnonymous ? 
						String.Format(@"<a href=""{0}"">{1}</a>", authorUrl, caption.User.Name) : "Anonymous" // 7
					);

				var content = new TextSyndicationContent(html, TextSyndicationContentKind.Html);

				SyndicationItem item = new SyndicationItem()
				{
					BaseUri = uri,
					Content = content,
					Copyright = new TextSyndicationContent(
						"Picture and caption copyrights are held by their original authors.",
						TextSyndicationContentKind.Plaintext),
					Id = uri.ToString(),
					LastUpdatedTime = caption.Event.Datetime,
					PublishDate = caption.Event.Datetime,
					Title = new TextSyndicationContent(
						caption.Text,
						TextSyndicationContentKind.Plaintext)
				};

				items.Add(item);

			}

			SyndicationFeed feed = new SyndicationFeed()
			{
				BaseUri = baseUri,
				Items = items,
				LastUpdatedTime = captions.First().Event.Datetime,
				Title = new TextSyndicationContent("Latest Captions @ " + ViewBag.SiteName, TextSyndicationContentKind.Plaintext)
			};


			return new RssActionResult() { Feed = feed };
		}

		/// <summary>
		/// Show a list of all the captions for pictures.  This is used for the "Latest captions" page.
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			var captions = _pictureService.GetAllCaptions(ViewBag.IsAdminStuffShown, null);
			List<CaptionForPictureViewModel> cfpvms = new List<CaptionForPictureViewModel>();

			foreach (var caption in captions)
			{
				cfpvms.Add(new CaptionForPictureViewModel(caption));
			}

			User viewingUser = Session["User"] as User;
			ViewBag.IsUserBelowThreshold = (viewingUser != null && viewingUser.Score < 0);

			ViewBag.ArePermalinksShown = true;
			ViewBag.AreMoreCaptionsLinksShown = true;
			ViewBag.AreCaptionAuthorLinksShown = true;

			DateTime startOfWeek = DateTime.Today.AddDays(DateTime.Today.DayOfWeek - DayOfWeek.Monday);
			DateTime endOfWeek = startOfWeek.AddDays(6);

			DateTime startOfMonth = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
			DateTime endOfMonth = new DateTime(DateTime.Now.Year, DateTime.Now.Month + 1, 1);

			ViewBag.RankedUsers = new Dictionary<string, List<RankedUser>>() {
				{ "today" , _accountService.GetRankedUsers(DateTime.Today, DateTime.Today.AddDays(1)) },
				{ "thisWeek", _accountService.GetRankedUsers(startOfWeek, endOfWeek) },
				{ "thisMonth", _accountService.GetRankedUsers(startOfMonth, endOfMonth) },
				{ "allTime", _accountService.GetRankedUsers() }
			};

			return View(cfpvms.OrderByDescending(c => c.Created));
		}

		/// <summary>
		/// Cat all the Captions for Pictures for a given user
		/// </summary>
		/// <param name="userName">The username (or numeric ID) whose captions you want to display</param>
		/// <returns></returns>
        public ActionResult IndexByUser(string userName)
        {
			List<CaptionForPictureViewModel> cfpvms = new List<CaptionForPictureViewModel>();

			User userToView;

			int userId = -1;
			if (int.TryParse(userName, out userId))
			{
				userToView = _accountService.GetUserById(userId);
			}
			else
			{
				userToView = _accountService.GetUserByName(userName);
			}

			if (userToView == null || (!ViewBag.IsAdminStuffShown && userToView.IsLocked))
			{
				throw new HttpException(404, "No user with name " + userName + " found.");
			}

			foreach (var caption in userToView.Captions)
			{
				if(
					!ViewBag.IsAdminStuffShown
					&& (
						!caption.IsVisible || !caption.Picture.IsVisible || caption.Picture.Activates > DateTime.UtcNow
						|| caption.Picture.IsPrivate || caption.IsAnonymous
						|| (caption.Picture.User != null && caption.Picture.User.IsLocked)
					)
				)
				{
					continue;
				}

				cfpvms.Add(new CaptionForPictureViewModel(caption));
			}


			User viewingUser = Session["User"] as User;
			ViewBag.IsUserBelowThreshold = (viewingUser != null && viewingUser.Score < 0);

			ViewBag.ArePermalinksShown = true;
			ViewBag.AreMoreCaptionsLinksShown = true;
			ViewBag.AreCaptionAuthorLinksShown = false;
			ViewBag.UserName = (!String.IsNullOrWhiteSpace(userToView.Name) ? userToView.Name : "User " + userToView.Id);

			return View(cfpvms.OrderByDescending(c => c.Created));
        }

    }
}

Capt/Controllers/CommentController.cs
/*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capt.Models;
using Capt.Helpers;
using System.Text.RegularExpressions;
using Capt.Services;

namespace Capt.Controllers
{
	/// <summary>
	/// Controller actions for getting and saving comments
	/// </summary>
	public class CommentController : Controller
    {

		private IPictureService _pictureService;

		/// <summary>
		/// Create a new CommentController with the specified picture service
		/// </summary>
		/// <param name="commentRepo">The picture service this controller should use</param>
		public CommentController(IPictureService pictureService)
		{
			_pictureService = pictureService;
		}

		/// <summary>
		/// Zero-argument constructor will try and choose the most appropriate services
		/// </summary>
		public CommentController()
			: this(new PictureService())
		{
		}

		/// <summary>
		/// Save a new comment to the database.
		/// </summary>
		/// <param name="captionId">The ID of the caption to which this comment should be attached</param>
		/// <param name="text">The text of the comment itself.</param>
		/// <returns></returns>
		[ValidateInput(false)]
        public string CreateForCaption(int captionId, string text)
        {

			if (!Request.IsAjaxRequest())
			{
				return GetForCaption(captionId);
			}

			// OK JS should have taken care of this but if not ho hum
			text = text.Trim();

			// Strip out any HTML tags the user may have tried to sneak in 
			Regex regHtml = new System.Text.RegularExpressions.Regex("<[^>]*>");
			text = regHtml.Replace(text, "");

			if (text.Length > 140)
			{
				text = text.Substring(0, 140).Trim();
			}

			User user = Session["User"] as User;

			if (user != null)
			{

				Comment newComment = new Comment()
				{
					Event = new Event(EventType.CommentCreated),
					IsVisible = true,
					Text = text,
					UserId = user.Id,
				};

				_pictureService.SaveCommentForCaption(newComment, captionId);

			}

			return GetForCaption(captionId);
        }

		/// <summary>
		/// Get the comments for a given caption
		/// </summary>
		/// <param name="captionId">The ID of the caption whose comments you want</param>
		/// <returns></returns>
		private string GetForCaption(int captionId)
		{
			var comments = _pictureService.GetCommentsForCaption(captionId, false);

			string list = "<ul class=\"caption_comment_list\">\n";
			foreach (var comment in comments)
			{
				list += "<li>\n" 
					+ "<span class=\"comment_text\">" + comment.Text + "</span>\n"
					+ "<span class=\"comment_timestamp\">" + HtmlExtensions.TimeSince(comment.Event.Datetime) + "</span>\n"
					+ "<span class=\"comment_author\">by " 
						+ (!String.IsNullOrWhiteSpace(comment.User.Name) ? comment.User.Name : "Anonymous")
					+ "</span>\n"
					+ "</li>\n";
			}

			list += "<ul>\n";

			return list;
		}

    }
}

Capt/Views/CaptionForPicture/DetailsPartial.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@using Capt.Helpers;

@model Capt.Models.CaptionForPictureViewModel

<div class="vote_control_container caption_vote_control_container">
    @if (!Model.IsViewingUserAuthor)
    {
        var UpArrowClasses = new List<String>() { "vote_arrow", "up_arrow" };
        if (!Request.IsAuthenticated) { UpArrowClasses.Add("requires_login"); }
        if (Model.IsUpVotedByViewingUser) { UpArrowClasses.Add("highlighted"); }
        if (ViewBag.IsUserBelowThreshold) { UpArrowClasses.Add("below_threshold"); }
                    
        @Ajax.ActionImageLink(Url.Content("~/Content/images/arrow-up-small.png"), "Vote this caption up!",
            "CreateForCaption", "Vote", new { captionId = Model.Id, isUpvote = true },
            new AjaxOptions { UpdateTargetId = "caption_points_" + Model.Id },
            new Dictionary<string, string>() { { "class", String.Join(" ", UpArrowClasses.ToList()) } })
    }
                
    <div id="caption_points_@(Model.Id)" class="vote_points small_vote_points">@Model.Score</div>
                
    @if (!Model.IsViewingUserAuthor)
    {
        var DownArrowClasses = new List<String>() { "vote_arrow", "down_arrow" };
        if (!Request.IsAuthenticated) { DownArrowClasses.Add("requires_login"); }
        if (Model.IsDownVotedByViewingUser) { DownArrowClasses.Add("highlighted"); }
        if (ViewBag.IsUserBelowThreshold) { DownArrowClasses.Add("below_threshold"); }
                    
        @Ajax.ActionImageLink(Url.Content("~/Content/images/arrow-down-small.png"), "Vote this caption down!",
            "CreateForCaption", "Vote", new { captionId = Model.Id, isUpvote = false },
            new AjaxOptions { UpdateTargetId = "caption_points_" + Model.Id },
            new Dictionary<string, string>() { { "class", String.Join(" ", DownArrowClasses.ToList()) } })
    }
</div>

<p class="caption_text">
    @if (ViewBag.AreMoreCaptionsLinksShown)
    {
        @Html.ActionLink(Model.Text, "Create", "PictureCaptions", new { pictureId = Model.Picture.Id }, new { @class = "caption_text_link" })
    }
    else
    {
        @Html.DisplayFor(modelItem => Model.Text)
    }
</p>

<span class="caption_footer">
    @Html.TimeSince(Model.Created)

    @if (ViewBag.AreCaptionAuthorLinksShown)
    {
        @:by
        if (Model.IsAnonymous)
        {
            @:Anonymous
        }
        else
        {
			@Html.ActionLink(Model.Author, "IndexByUser", "CaptionForPicture", new { userName = Model.Author }, new { @class = "caption_list_control" }) 
            @:(@Model.AuthorPoints points)
        }
    }

    @if (ViewBag.AreMoreCaptionsLinksShown)
    {
        @Html.ActionLink("more captions for this picture", "Create", "PictureCaptions", new { pictureId = Model.Picture.Id }, new { @class = "caption_list_control secondary_caption_list_control" })
    }
    @if (ViewBag.ArePermalinksShown)
    {
        @Html.ActionLink("permalink", "CaptionDetails", "PictureCaptions", new { captionId = Model.Id }, new { @class = "caption_list_control secondary_caption_list_control" })
    }
    <a href="" onclick="$('#caption_comments_@(Model.Id)').slideDown(); return false;" class="caption_list_control secondary_caption_list_control">
        @if (Model.Comments.Count == 0)
        {
            @:add comment
        }
        else
        {
            @Model.Comments.Count @(Model.Comments.Count == 1 ? " comment" : " comments")
        }
    </a>

</span>
<div class="caption_comments" id="caption_comments_@(Model.Id)" style="display: none;">

    <div id="caption_comment_text_@(Model.Id)">
        <ul class="caption_comment_list">
            @foreach (var comment in Model.Comments)
            {
                <li>
                    <span class="comment_text">@comment.Text</span>
                    <span class="comment_timestamp">@Html.TimeSince(comment.Event.Datetime)</span>
                    <span class="comment_author">
                        by 
                        @if (!String.IsNullOrWhiteSpace(comment.User.Name))
                        {
                            @Html.ActionLink(comment.User.Name, "IndexByUser", "CaptionForPicture", new { }, new { userName = comment.User.Name } );
                        }
                        else
                        {
                            @:Anonymous   
                        }
                    </span>
                    
                </li>
            }
        </ul>
    </div>

    @using (Ajax.BeginForm("CreateForCaption", "Comment", new { captionId = Model.Id },
        new AjaxOptions { 
            UpdateTargetId = "caption_comment_text_" + Model.Id, 
            OnComplete = "Capt.CommentPosted('caption_comments_" + Model.Id + "');",
            OnFailure = "Capt.CommentNotPosted('caption_comments_" + Model.Id + "');",
            OnBegin = "Capt.CommentPostBegin('caption_comments_" + Model.Id + "');"
        })) 
    {
        var textareaClasses = new List<String>();
        var buttonClasses = new List<String>();
        
        textareaClasses.Add("caption_comment_text");
        buttonClasses.Add("comment_save_button");
        
        if (!Request.IsAuthenticated) 
        { 
            textareaClasses.Add("requires_login");
            buttonClasses.Add("requires_login"); 
        }
        
        <textarea id="caption_comment_text_@(Model.Id)" class="@(String.Join(" ", textareaClasses))" name="text"></textarea>
        <br />
        <span class="caption_comment_text_counter" id="caption_comment_text_@(Model.Id)_counter">140</span>
        <input class="@(String.Join(" ", buttonClasses))" type="submit" value="Say It" />
     }
     <a href="" onclick="$('#caption_comments_@(Model.Id)').slideUp(); return false;" class="caption_list_control secondary_caption_list_control">
        hide comment stuff
     </a>
</div>
@if (ViewBag.IsAdminStuffShown)
{
    if (!String.IsNullOrWhiteSpace(Model.AdminNote))
    {
        <br /><span class="admin_note">@Model.AdminNote</span>
    }

    if (!Model.IsVisible || Model.IsAuthorLocked)
    {
        <br />
        if (!Model.IsVisible)
        {    
            <span class="admin_note">invisible</span>
        }

        if (Model.IsAuthorLocked)
        {
            <span class="admin_note">user locked</span>
        }
    }
                    
    <ul class="menu">
        <li>@Html.ActionLink("edit", "Edit", "Caption", new { id = Model.Id }, new { @class = "admin_option" })</li>
        <li>@Html.ActionLink("details", "Details", "Caption", new { id = Model.Id }, new { @class = "admin_option" })</li>
        <li>@Html.ActionLink("delete", "Delete", "Caption", new { id = Model.Id }, new { @class = "admin_option" })</li>
    </ul>
}

Capt/Views/CaptionForPicture/Index.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model IEnumerable<Capt.Models.CaptionForPictureViewModel>

@{
    ViewBag.Title = "Latest Captions";
}

<script src="@Url.Content("~/Scripts/CaptionInput.js")" type="text/javascript"></script>

<div id="scoreboard">
    @Html.Partial("~/Views/User/UserForScoreBoardPartial.cshtml", ViewData["RankedUsers"])
</div>

@Html.Partial("~/Views/Shared/PictureCaptionMenuPartial.cshtml")

<table id="picture_index_table">

    @foreach (var item in Model) {
        <tr>
			<td class="picture_list_image_cell">
				<div class="picture_list_image_container">
					<a href="@Url.Action("Create", "PictureCaptions", new { pictureId = item.Picture.Id })">
						<img class="picture_list_image" src="@item.Picture.Url" />
					</a>
				</div>
                
                @if (!String.IsNullOrWhiteSpace(item.Picture.Attribution))
                {
                    <br /><span class="user_caption_list_picture_attribution">@Html.Raw(item.Picture.Attribution)</span>
                }
                <br /><a href="@item.Picture.License.InfoUrl"><img src="@Html.Raw(item.Picture.License.ImageUrl)" /></a>
                

            </td>
            <td style="padding-left: 40px;">
                @Html.Partial("~/Views/CaptionForPicture/DetailsPartial.cshtml", item)
            </td>
        </tr>
    }

</table>


Capt/Views/CaptionForPicture/IndexByUser.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model IEnumerable<Capt.Models.CaptionForPictureViewModel>

@{
    ViewBag.Title = ViewBag.UserName + "'s Captions";
}
<script src="@Url.Content("~/Scripts/CaptionInput.js")" type="text/javascript"></script>

<h2>@ViewBag.UserName's Captions</h2>

<table id="picture_index_table">

    @foreach (var item in Model) {
        
        
        <tr>
			<td class="picture_list_image_cell">
				<div class="picture_list_image_container">
					<a href="@Url.Action("Create", "PictureCaptions", new { pictureId = item.Picture.Id })">
						<img class="picture_list_image" src="@item.Picture.Url" />
					</a>
				</div>
                
                @if (!String.IsNullOrWhiteSpace(item.Picture.Attribution))
                {
                    <br /><span class="user_caption_list_picture_attribution">@Html.Raw(item.Picture.Attribution)</span>
                }
                <br /><a href="@item.Picture.License.InfoUrl"><img src="@Html.Raw(item.Picture.License.ImageUrl)" /></a>
                

            </td>
            <td style="padding-left: 40px;">
                @Html.Partial("~/Views/CaptionForPicture/DetailsPartial.cshtml", item)
            </td>
        </tr>
    }

</table>

Capt/Views/CaptionForPicture/IndexPartial.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model IEnumerable<Capt.Models.CaptionForPictureViewModel>

<ul id="caption_list">
	@foreach (var item in Model)
	{
		<li style="clear: both;">
            @Html.Partial("~/Views/CaptionForPicture/DetailsPartial.cshtml", item)
		</li>
	}
</ul>